### ISSUE TITLE
[BUG] !move to same channel can be done

### ISSUE THREAD

**Issue by manderio** [unixporn/robbb#109]
## Expected behaviour
Return with an error message when you try to do !move to the channel you are currently in

## Current behaviour
It just moves to the same channel. Also accidentally triggered a discord bug where it moved the conversdation to dms for the user I moved so that was fun. 
![image](https://user-images.githubusercontent.com/59826300/117936558-493ee880-b305-11eb-9785-0dd8a9534971.png)

## Additional information
You're all lovely and work really hard, please have a nice day and a hug from me thank you!
![image](https://media.tenor.com/images/e1b097721fc9dc48134181c69aea7bbd/tenor.gif)

### edit
*in buffet voice* I BROKE DISCORD!
![image](https://user-images.githubusercontent.com/59826300/117936970-c36f6d00-b305-11eb-82c3-0a71345fb3a4.png)

It triggers when you try to click the link to get to the new conversation. Might not be too good to trigger discord bugs with bot links hehe

**Comment by elkowar** [comment]
Issue with the DM stuff is that serenity generates the link containing `@me` - which is broken. The tracking issue for that is https://github.com/serenity-rs/serenity/issues/1331. Rather than working around this serenity issue, I'd argue we should just wait for a bit until that is fixed. 

Regarding linking to the same channel: I don't think that's necessarily an issue, although giving a nice error message here is a good opportunity for some jokus, so maybe a response like
```
# Unnecessary move

Moving _exactly_ where you're at - kinda useless, no?
```
could be fun to add. any 🧅s on that?

**Comment by manderio** [comment]
1. fix issue stop being lazy reeeee (this was joke, don't take me seriously, [have another hug instead for being great](https://tenor.com/vfFB.gif))
2. would be nice to have that, especially for dumbasses like me who mistyped commands a billion times this morning. 
3. can we autodelete errored commands after x amount of time so they don't clutter a channel? different issue. but yea.

**Comment by 6gk** [comment]
> have another hug instead for being great

I read this as bug the first time ~~and frankly I preferred it that way~~
