### ISSUE TITLE
[BUG] Highlight Doesn't work with User pings

### ISSUE THREAD

**Issue by Tanish2002** [unixporn/robbb#121]
## Expected behaviour
I get a DM whenever someone ping pome

## Current behaviour
I added a highlight for pome but I don't get a DM for it

proof(I don't know why I am attaching these) -:
![image](https://user-images.githubusercontent.com/55488165/119253259-0b2ba980-bbce-11eb-90f0-5e36e528786f.png)
![image](https://user-images.githubusercontent.com/55488165/119253241-ec2d1780-bbcd-11eb-91ab-378060e23dae.png)

**Comment by elkowar** [comment]
As gk showed today, it does work if you use the user-id rather than a ping. I'd say that should be enough to fill the usecase if you really need it - and if you don't, making it an extra feature is probably not the best idea (this may obviously also be used to specifically harass people or something - idk, but nothing I wanna necessarily specifically encourage)
